services:
  db:
    image: postgres:18
    container_name: db
    hostname: db
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: worker
      POSTGRES_PASSWORD: d26N7MKLzlhk
      POSTGRES_DB: bbs
    volumes:
      - pg_data:/var/lib/postgresql/18/docker

volumes:
  pg_data:
